version: '3'

services:
    db:
        build: ./docker/mysql/
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        # restart: always
        tty: true
        environment: 
            MYSQL_ROOT_PASSWORD: django
            MYSQL_USER: django
            MYSQL_DATABASE: django
            MYSQL_PASSWORD: django
        ports:
            - "3306:3306"
    web:
        build: ./docker/python/
        tty: true
        volumes: 
            - ./src:/code
        ports: 
            - "8000:8000"
        depends_on:
            - db

        


    
